version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: spotify_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: spotify_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:7.0
    container_name: spotify_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./spotify-backend
    container_name: spotify_backend
    restart: always
    environment:
      POSTGRES_HOST: postgres-db
      MONGO_HOST: mongo-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      ADMIN_DEFAULT_USERNAME: ${ADMIN_DEFAULT_USERNAME}
      ADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASSWORD}
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres-db
      - mongo-db

  frontend:
    build:
      context: ./spotify-frontend
    container_name: spotify_frontend
    restart: always
    ports:
      - "127.0.0.1:5173:80"
    depends_on:
      - backend


volumes:
  postgres_data:
    name: javaspotify_postgres_data
    external: true
  mongo_data:
    name: javaspotify_mongo_data
    external: true