server:
  port: 8080
  address: 127.0.0.1

spring:
  datasource:
    # Jeśli zmienna POSTGRES_HOST nie istnieje, użyj "localhost" (dla IntelliJ)
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/spotify_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      # Zmienna MONGO_HOST przełącza adres między Dockerem a IntelliJ
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:27017/spotify_db?authSource=admin


  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/spotify"
            scope:
              - user-read-email
              - user-top-read
              - user-read-recently-played
              - user-library-read
              - user-read-currently-playing
              - user-read-private
            client-name: Spotify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: display_name