server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # TO JEST MAGICZNA LINIJKA NAPRAWIAJĄCA BŁĄD 404:
        # "Zawsze, gdy ktoś prosi o jakikolwiek adres, którego nie masz na dysku,
        # odeślij mu główny index.html, a React Router sam ogarnie resztę!
        try_files $uri $uri/ /index.html;
    }
}