server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 404 solution: if asked for adress you do not have on a disk, return index.html, ReactRouter will take over
        try_files $uri $uri/ /index.html;
    }
}