name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Javy 25
        uses: actions/setup-java@v4
        with:
          java-version: '25-ea' # Używamy Early Access dla Javy 25
          distribution: 'temurin'
          cache: maven

      - name: Uruchomienie testów Backend (Maven)
        working-directory: ./spotify-backend
        run: mvn test

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './spotify-frontend/package-lock.json'

      - name: Instalacja zależności i uruchomienie testów Frontend
        working-directory: ./spotify-frontend
        run: |
          npm ci
          npm test